### PR TITLE
added repo_name, layout.conf file, added ebuilds

### PR DESCRIPTION
**Pull request by timeraider4u**
added metadata/layout.conf
added profiles/repo_name
added ebuilds for 
- eclipse/plugins/javax.annotation_1.2.0.v201401042248.jar
- eclipse/plugins/org.tukaani.xz_1.3.0.v201308270617.jar 
- eclipse/plugins/org.w3c.dom.events_3.0.0.draft20060413_v201105210656.jar 
- eclipse/plugins/org.w3c.dom.smil_1.0.1.v200903091627.jar
- eclipse/plugins/org.w3c.dom.svg_1.1.0.v201011041433.jar 

Review, comments, feedback and changes/improvements are welcome!

### CODE REVIEW

**Comment by chewi** [comment]
@hartwork, not sure if you intend to oversee this overlay for the time being?

@timeraider4u, thanks for the contribution but unfortunately you're not making proper use of the Java eclasses, which can lead to problems. They are documented though I admit that it could be better. Some things that stand out:
- Don't put virtual/jdk in RDEPEND, except in very rare cases. virtual/jre should go there.
- You don't need to cd to ${S}, you're already there in src_prepare and later phases.
- You don't need to add die to Portage helpers like dodir.
- Never call ant directly, use eant instead.
- However, you shouldn't need to define src_compile at all in many cases.
- If you need to pass arguments to ant, set EANT_EXTRA_ARGS.
- Custom build.xml files in FILESDIR isn't the way to go here. Use the java-pkg-simple eclass.
- Use doins rather than cp.
- But use java-pkg_dojar for installing jars.

**Comment by hartwork** [comment]
Hello @timeraider4u ,
thanks for your contribution!

From my look at the ebuilds, there are a number of donts in there that would need fixing, as @chewi noted already. It's no showstopper though. I wonder how to best continue so that it's the best experience for everyone involved. I have focused on one ebuild for now - `javax-annotation-1.2.0.ebuild` - and polished that and fed it @chewi for review. The result is further down, comments too.
Would you be okay with making a new pull request with one other package of these, applying the feedback from @chewi's and my post?

The polished ebuild:

```
# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI="5"

JAVA_PKG_IUSE="doc source"
inherit versionator java-pkg-2 java-pkg-simple

MY_PV="$(get_version_component_range 1-2)"
SPEC_V="1.0.0.Final"

DESCRIPTION="Common java annotations (package javax.annotations)"
HOMEPAGE="https://docs.oracle.com/javase/6/docs/api/javax/annotation/package-summary.html"
SRC_URI="https://repository.jboss.org/nexus/content/repositories/public/org/jboss/spec/javax/annotation/jboss-annotations-api_${MY_PV}_spec/${SPEC_V}/jboss-annotations-api_${MY_PV}_spec-${SPEC_V}-sources.jar" 

LICENSE="CDDL"
SLOT="0"
KEYWORDS="~amd64 ~x86"

RDEPEND=">=virtual/jre-1.5"
DEPEND=">=virtual/jdk-1.5"
```

Comments:
- Please indent with single tabs
- No dead / commented out code, please
- Use `${P}`, `${PV}`, `${MY_PV}` in `${SRC_URI}` wherever possible. When copying the ebuild to a new version, `${SRC_URI}` should have the highest possible chance of working right out of the box.
- Smallest supported Java version, please
- For `DEPEND` JDK, for `REDEPEND` _JRE_
- Adding `~x86` when packaging on `~amd64` is assumed safe and good practice

> Use doins rather than cp.

Adding to that: For a good overview of ebuild helpers that are worth knowing about check
- `/usr/lib64/portage/python2.7/ebuild-helpers/*`
- `/usr/lib64/portage/python2.7/phase-helpers.sh`

> You don't need to add die to Portage helpers like dodir.

Adding to that: The keyword is EAPI version 4 or later. Since then, `die` is called internally. (Prefix comands with `nonfatal` to bypass that behaviour; not necessary often, though.)

**Comment by hartwork** [comment]
javax-annotation just turned out to be `dev-java/jsr250` / https://jcp.org/en/jsr/detail?id=250.

f8812a7eccb001f7f8d1d72bd3264beef8634b56

**Comment by chewi** [comment]
@hartwork, not sure if you're aware of the existing jsr250 in the tree. The existing ebuild correctly includes `app-arch/unzip` in DEPEND as this is used to extract rather than `jar`. Easy to forget that though. :smile:

**Comment by timeraider4u** [comment]
Thank you very much for your review and the good advices. I will improve the ebuilds next week and start pull issues again then, if that is okay for you ;-).

**Comment by timeraider4u** [comment]
one thing I noticed with dev-java/jsr250 is that the /usr/share/jsr250/lib/jsr250.jar neither contains javax.ManagedBean.class nor javax.Priority.class nor the javax.sql package.

**Comment by hartwork** [comment]
> @hartwork, not sure if you're aware of the existing jsr250 in the tree.

@chewi
Yes. That's where I got the unfindable name from :wink:
I didn't bump 1.0 in the main repository because I didn't want to cause breakage (for some reverse depdnency) for nothing. Should I bump it there, instead?

> The existing ebuild correctly includes app-arch/unzip in DEPEND as this is used to extract rather than jar. Easy to forget that though. :smile:

abde7c6ef3036f643bd9dd36b9183860497b0f60

Oops. I am considering to add .jar support to `unpacker.eclass`. You would `inherit unpacker` then to achieve the same and if another implementation of zip comes along, no one will have to switch to a virtual or so at multiple places. Would it cause problems that I am not thinking of yet?

> next week and start pull issues again then, if that is okay for you ;-).

@timeraider4u 
Yes!

> one thing I noticed with dev-java/jsr250 is that the /usr/share/jsr250/lib/jsr250.jar neither contains javax.ManagedBean.class nor javax.Priority.class nor the javax.sql package.

Excellent catch. I will have a closer look. My current guess is that the jar you used originally is newer than the one I switched to. I hope we find evidence one way or another.

**Comment by hartwork** [comment]
> one thing I noticed with dev-java/jsr250 is that the /usr/share/jsr250/lib/jsr250.jar neither contains javax.ManagedBean.class nor javax.Priority.class nor the javax.sql package.

@timeraider4u 
Update: I had a closer look now. I believe you looked at `/usr/share/jsr250/lib/jsr250.jar` of `dev-java/jsr250` _version 1.0_, not [1.2 of this very overlay](https://github.com/gentoo/eclipse-overlay/blob/master/dev-java/jsr250/jsr250-1.2.ebuild). The latter does contain these files over here.

**Comment by timeraider4u** [comment]
@hartwork: ah perfect, I have not seen yet that you checked in a new ebuild (when looking on my smartphone) ;-).

**Pull request closed without merging**
