### PR TITLE
Neon update

### PR DESCRIPTION
**Pull request by stefan-langenmaier**
Just a bump for the current stable version.

The unbundled dependencies have to be checked again, I deactivated them for the moment.

### CODE REVIEW

**Comment by hartwork** [comment]
Hi Stefan,

thanks for this PR of yours.

I had a bit of a closer look now. This is what I would like to share:
- icu4j-56.1 should probably go into the Gentoo master repository, instead
- Comparing eclipse ebuild 4.6.1a to 4.5.2-r1 shows that it adds undone todos. It looks too unfinished to merge to me, e.g. commented out code should be avoided.
- Two commits combine changes to several packages with no explicit need to
- Commit messages do not yet start with "cat/pkg: " prefix

So I have only merged the lombok bump and the fix to metadata.xml for now:
- https://github.com/gentoo/eclipse-overlay/commit/155a898c16e2df3072dcaf529c1e7ae33d2c0883
- https://github.com/gentoo/eclipse-overlay/commit/298efd43065db1eceb059a4258d0c99777134b3a

Best, Sebastian

**Comment by stefan-langenmaier** [comment]
Hello Sebastian,

thanks for looking into it.
- For icu4j I created a bug report here: https://bugs.gentoo.org/show_bug.cgi?id=599242
- Yes I wanted to have your opinion first, it's not ready yet. But what would you recommend? With the icu4j jar unbundeled everything seems to be working but I have some error/warning messages [1] when I start eclipse from the command line. I tried to unbundle some other jars (only locally) but they have caused problems with the installation (like no working maven integration). Would it be okay to not unbundle it in the first step to get it into the repo?
- Sorry you are right, sloppy commits. I will rebase my pull request and try to clean it up a little bit.
- Didn't know that, thanks. I'll try to fix it.

[1]: WARNING: Duplicate name in Manifest: SHA-256-Digest.
Ensure that the manifest does not have duplicate entries, and
that blank lines separate individual sections in both your
manifest and in the META-INF/MANIFEST.MF entry in the jar file.
Nov 13, 2016 12:52:42 AM java.util.jar.Attributes read

**Comment by hartwork** [comment]
For the existing unbundles maybe update-fix those that can be with reasonable effort, and drop those with unreasonable effort. At least we don' have dead code around then.

**Comment by stefan-langenmaier** [comment]
Hi,
- I saw that you added icu4j-56.1 to the official repo, so I removed it from the pull request.
- I readded/updated the old unbundled dependencies. It is working for me. The icu4j dependency is still creating the messages.
- The leftover changes should be cleaned up by now.

**Comment by hartwork** [comment]
There were two blank lines introduced that I removed, the rest is as-is. Thanks!
22fb56bfd37cb097aa2a6cd208590475654c89f0

**Pull request closed without merging**
