### PR TITLE
add travis integration

### PR DESCRIPTION
**Pull request by stefan-langenmaier**
I took the travis config from the mrueg overlay, so that people like me who forget to run repoman, always see the result.

Maybe this can also be configured for this repo.

### CODE REVIEW

**Comment by timeraider4u** [comment]
@stefan-langenmaier: you may also add the following line to the README.md
`[Build Status](https://travis-ci.org/gentoo/eclipse-overlay)`
once Travis builds for this repository are enabled

**Comment by stefan-langenmaier** [comment]
Yes, good idea.

**Comment by hartwork** [comment]
Very nice! I have merged that, activated the repository on Travis CI side, added that button as recommended and fixed existing repoman errors. Pull request should receive repoman hints as well now.

**Comment by hartwork** [comment]
PS: If you feel like getting `app-portage/overlint` in as well, that would be welcome.

**Pull request merged**
